// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQKqDOEpPgtPIVcZWImse4boiELTIumfA',
    appId: '1:298619652724:web:9158e62cc1fdf9c716df21',
    messagingSenderId: '298619652724',
    projectId: 'brademoproj1',
    authDomain: 'brademoproj1.firebaseapp.com',
    storageBucket: 'brademoproj1.firebasestorage.app',
    measurementId: 'G-1B11MTTWK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZD6x6LcazV55_ru_m-6cVKthNzfZ4vw4',
    appId: '1:298619652724:android:1c8948598146a64f16df21',
    messagingSenderId: '298619652724',
    projectId: 'brademoproj1',
    storageBucket: 'brademoproj1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBesT33NBp3Q6-6nQ-bZUj9A0P3HZMSLWs',
    appId: '1:298619652724:ios:86cc7e144a35b1a516df21',
    messagingSenderId: '298619652724',
    projectId: 'brademoproj1',
    storageBucket: 'brademoproj1.firebasestorage.app',
    iosBundleId: 'com.example.firebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBesT33NBp3Q6-6nQ-bZUj9A0P3HZMSLWs',
    appId: '1:298619652724:ios:86cc7e144a35b1a516df21',
    messagingSenderId: '298619652724',
    projectId: 'brademoproj1',
    storageBucket: 'brademoproj1.firebasestorage.app',
    iosBundleId: 'com.example.firebaseFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQKqDOEpPgtPIVcZWImse4boiELTIumfA',
    appId: '1:298619652724:web:efc58c9c8e3c739416df21',
    messagingSenderId: '298619652724',
    projectId: 'brademoproj1',
    authDomain: 'brademoproj1.firebaseapp.com',
    storageBucket: 'brademoproj1.firebasestorage.app',
    measurementId: 'G-LGZC24Z3XF',
  );

}